services:
  - type: web
    name: villen-django-app
    runtime: python
    region: singapore
    branch: master
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn villen.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: villen.settings
      - key: PRODUCTION
        value: 'true'
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: villen.me,villen-django-app.onrender.com
