# Generated by Django 5.2.1 on 2025-12-02 18:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=64)),
                ('device_label', models.CharField(blank=True, default='', max_length=100)),
                ('trust_level', models.CharField(choices=[('trusted', 'Trusted'), ('pending', 'Pending Verification'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(max_length=64)),
                ('otp_code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('was_successful', models.BooleanField(default=False)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description of the notes')),
                ('category', models.CharField(choices=[('python', 'Python'), ('c', 'C Programming'), ('cpp', 'C++'), ('java', 'Java'), ('javascript', 'JavaScript'), ('html', 'HTML/CSS'), ('sql', 'SQL'), ('mongodb', 'MongoDB'), ('android', 'Android'), ('react', 'React'), ('django', 'Django'), ('nodejs', 'Node.js'), ('dsa', 'Data Structures'), ('ml', 'Machine Learning'), ('cyber', 'Cybersecurity'), ('networking', 'Networking'), ('os', 'Operating System'), ('dbms', 'DBMS'), ('other', 'Other')], default='other', max_length=50)),
                ('icon_class', models.CharField(choices=[('fa-brands fa-python', 'Python'), ('fa-solid fa-c', 'C'), ('fa-solid fa-code', 'C++'), ('fa-brands fa-java', 'Java'), ('fa-brands fa-js', 'JavaScript'), ('fa-brands fa-html5', 'HTML'), ('fa-solid fa-database', 'SQL/Database'), ('fa-brands fa-android', 'Android'), ('fa-brands fa-react', 'React'), ('fa-brands fa-node-js', 'Node.js'), ('fa-solid fa-shield-halved', 'Cybersecurity'), ('fa-solid fa-network-wired', 'Networking'), ('fa-solid fa-laptop-code', 'Programming'), ('fa-solid fa-brain', 'ML/AI'), ('fa-solid fa-book', 'Notes'), ('fa-solid fa-file-pdf', 'PDF')], default='fa-solid fa-book', help_text='Font Awesome icon class', max_length=100)),
                ('icon_image_url', models.URLField(blank=True, help_text='Alternative: Image URL for icon (overrides icon_class)', max_length=500, null=True)),
                ('file', models.FileField(help_text='Upload PDF, images or document files', upload_to='notes/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail image', null=True, upload_to='notes_thumbnails/')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin must approve before showing')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage/featured section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('was_successful', models.BooleanField(default=False)),
                ('otp_entered', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('activated', 'Premium Activated'), ('upgraded', 'Tier Upgraded'), ('downgraded', 'Tier Downgraded'), ('renewed', 'Premium Renewed'), ('expired', 'Premium Expired'), ('revoked', 'Premium Revoked'), ('extended', 'Duration Extended')], max_length=20)),
                ('previous_tier', models.CharField(blank=True, max_length=20)),
                ('new_tier', models.CharField(blank=True, max_length=20)),
                ('previous_expiry', models.DateTimeField(blank=True, null=True)),
                ('new_expiry', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Premium History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_locked', 'Account Locked'), ('logout', 'Logout'), ('logout_all', 'Logout All Sessions'), ('otp_success', 'OTP Verified'), ('otp_failed', 'OTP Failed'), ('otp_locked', 'OTP Locked'), ('otp_resend', 'OTP Resent'), ('password_reset', 'Password Reset'), ('password_reset_request', 'Password Reset Request'), ('password_change', 'Password Changed'), ('premium_request', 'Premium Request'), ('premium_approved', 'Premium Approved'), ('premium_rejected', 'Premium Rejected'), ('premium_cancelled', 'Premium Cancelled'), ('premium_revoked', 'Premium Revoked'), ('premium_expired', 'Premium Expired'), ('premium_upgraded', 'Premium Upgraded'), ('registration', 'User Registration'), ('profile_update', 'Profile Updated'), ('new_device_login', 'New Device Login'), ('suspicious_activity', 'Suspicious Activity'), ('session_terminated', 'Session Terminated'), ('device_trusted', 'Device Trusted'), ('device_verification_sent', 'Device Verification Sent'), ('device_verification_failed', 'Device Verification Failed'), ('device_revoked', 'Device Revoked'), ('device_blocked', 'Device Blocked')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('seo', 'SEO'), ('app', 'App Development'), ('design', 'UI/UX Design')], default='web', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(help_text='Google Drive or YouTube video URL', max_length=500)),
                ('category', models.CharField(choices=[('hacking', 'Hacking'), ('fun', 'Fun'), ('study', 'Study'), ('course', 'Course')], default='fun', max_length=20)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Optional thumbnail image URL', max_length=500, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('contributor', 'Contributor'), ('moderator', 'Moderator'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='viewer', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('premium_request_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='none', max_length=20)),
                ('premium_tier', models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='none', max_length=20)),
                ('premium_expires_at', models.DateTimeField(blank=True, null=True)),
                ('premium_activated_at', models.DateTimeField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('login_locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_user_agent', models.TextField(blank=True)),
                ('totp_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('reputation_score', models.IntegerField(default=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
