# Generated by Django 5.2.1 on 2025-06-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text="Enter FontAwesome class (e.g., 'fas fa-code')", max_length=100),
        ),
    ]
