# Generated by Django 5.2.1 on 2025-11-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loginattemptlog_alter_otp_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_locked', 'Account Locked'), ('logout', 'Logout'), ('otp_success', 'OTP Verified'), ('otp_failed', 'OTP Failed'), ('otp_locked', 'OTP Locked'), ('otp_resend', 'OTP Resent'), ('password_reset', 'Password Reset'), ('password_reset_request', 'Password Reset Request'), ('premium_request', 'Premium Request'), ('premium_approved', 'Premium Approved'), ('premium_rejected', 'Premium Rejected'), ('premium_cancelled', 'Premium Cancelled'), ('registration', 'User Registration')], max_length=30),
        ),
    ]
