# Generated by Django 5.2.1 on 2025-12-05 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_video_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceverificationotp',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_videos',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='core.video'),
        ),
        migrations.AddField(
            model_name='deviceverificationotp',
            name='otp_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='otp_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
