# Generated by Django 5.2.8 on 2025-11-27 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_securitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_tier',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='premium_request_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_locked', 'Account Locked'), ('logout', 'Logout'), ('logout_all', 'Logout All Sessions'), ('otp_success', 'OTP Verified'), ('otp_failed', 'OTP Failed'), ('otp_locked', 'OTP Locked'), ('otp_resend', 'OTP Resent'), ('password_reset', 'Password Reset'), ('password_reset_request', 'Password Reset Request'), ('password_change', 'Password Changed'), ('premium_request', 'Premium Request'), ('premium_approved', 'Premium Approved'), ('premium_rejected', 'Premium Rejected'), ('premium_cancelled', 'Premium Cancelled'), ('premium_revoked', 'Premium Revoked'), ('premium_expired', 'Premium Expired'), ('premium_upgraded', 'Premium Upgraded'), ('registration', 'User Registration'), ('profile_update', 'Profile Updated'), ('new_device_login', 'New Device Login'), ('suspicious_activity', 'Suspicious Activity'), ('session_terminated', 'Session Terminated')], max_length=30),
        ),
        migrations.CreateModel(
            name='PremiumHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('activated', 'Premium Activated'), ('upgraded', 'Tier Upgraded'), ('downgraded', 'Tier Downgraded'), ('renewed', 'Premium Renewed'), ('expired', 'Premium Expired'), ('revoked', 'Premium Revoked'), ('extended', 'Duration Extended')], max_length=20)),
                ('previous_tier', models.CharField(blank=True, max_length=20)),
                ('new_tier', models.CharField(blank=True, max_length=20)),
                ('previous_expiry', models.DateTimeField(blank=True, null=True)),
                ('new_expiry', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Premium History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
    ]
