# Generated by Django 5.2.1 on 2025-12-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_deviceverificationotp_otp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_videos',
        ),
        migrations.AlterField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.DeleteModel(
            name='BackupCode',
        ),
    ]
