# Generated by Django 5.2.1 on 2025-06-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_image_url_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('seo', 'SEO'), ('app', 'App Development'), ('design', 'UI/UX Design')], default='web', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
