# Generated by Django 5.2.1 on 2025-11-28 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_last_login_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_locked', 'Account Locked'), ('logout', 'Logout'), ('logout_all', 'Logout All Sessions'), ('otp_success', 'OTP Verified'), ('otp_failed', 'OTP Failed'), ('otp_locked', 'OTP Locked'), ('otp_resend', 'OTP Resent'), ('password_reset', 'Password Reset'), ('password_reset_request', 'Password Reset Request'), ('password_change', 'Password Changed'), ('premium_request', 'Premium Request'), ('premium_approved', 'Premium Approved'), ('premium_rejected', 'Premium Rejected'), ('premium_cancelled', 'Premium Cancelled'), ('premium_revoked', 'Premium Revoked'), ('premium_expired', 'Premium Expired'), ('premium_upgraded', 'Premium Upgraded'), ('registration', 'User Registration'), ('profile_update', 'Profile Updated'), ('new_device_login', 'New Device Login'), ('suspicious_activity', 'Suspicious Activity'), ('session_terminated', 'Session Terminated'), ('device_trusted', 'Device Trusted'), ('device_verification_sent', 'Device Verification Sent'), ('device_verification_failed', 'Device Verification Failed'), ('device_revoked', 'Device Revoked'), ('device_blocked', 'Device Blocked')], max_length=30),
        ),
        migrations.CreateModel(
            name='DeviceVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(max_length=64)),
                ('otp_code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=64)),
                ('device_label', models.CharField(blank=True, default='', max_length=100)),
                ('trust_level', models.CharField(choices=[('trusted', 'Trusted'), ('pending', 'Pending Verification'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'unique_together': {('user', 'fingerprint_hash')},
            },
        ),
    ]
