# Generated by Django 5.2.1 on 2025-11-28 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_securitylog_action_deviceverificationotp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description of the notes')),
                ('category', models.CharField(choices=[('python', 'Python'), ('c', 'C Programming'), ('cpp', 'C++'), ('java', 'Java'), ('javascript', 'JavaScript'), ('html', 'HTML/CSS'), ('sql', 'SQL'), ('mongodb', 'MongoDB'), ('android', 'Android'), ('react', 'React'), ('django', 'Django'), ('nodejs', 'Node.js'), ('dsa', 'Data Structures'), ('ml', 'Machine Learning'), ('cyber', 'Cybersecurity'), ('networking', 'Networking'), ('os', 'Operating System'), ('dbms', 'DBMS'), ('other', 'Other')], default='other', max_length=50)),
                ('icon_class', models.CharField(choices=[('fa-brands fa-python', 'Python'), ('fa-solid fa-c', 'C'), ('fa-solid fa-code', 'C++'), ('fa-brands fa-java', 'Java'), ('fa-brands fa-js', 'JavaScript'), ('fa-brands fa-html5', 'HTML'), ('fa-solid fa-database', 'SQL/Database'), ('fa-brands fa-android', 'Android'), ('fa-brands fa-react', 'React'), ('fa-brands fa-node-js', 'Node.js'), ('fa-solid fa-shield-halved', 'Cybersecurity'), ('fa-solid fa-network-wired', 'Networking'), ('fa-solid fa-laptop-code', 'Programming'), ('fa-solid fa-brain', 'ML/AI'), ('fa-solid fa-book', 'Notes'), ('fa-solid fa-file-pdf', 'PDF')], default='fa-solid fa-book', help_text='Font Awesome icon class', max_length=100)),
                ('icon_image_url', models.URLField(blank=True, help_text='Alternative: Image URL for icon (overrides icon_class)', max_length=500, null=True)),
                ('file', models.FileField(help_text='Upload PDF, images or document files', upload_to='notes/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail image', null=True, upload_to='notes_thumbnails/')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin must approve before showing')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage/featured section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
