# Generated by Django 5.2.1 on 2025-11-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('contributor', 'Contributor'), ('moderator', 'Moderator'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='viewer', max_length=20),
        ),
    ]
