# Generated by Django 5.2.1 on 2025-11-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_is_2fa_enabled_and_more'),
        ('tools', '0004_tool_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='purchased_notes',
            field=models.ManyToManyField(blank=True, related_name='purchasers', to='core.note'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='purchased_tools',
            field=models.ManyToManyField(blank=True, related_name='purchasers', to='tools.tool'),
        ),
    ]
