[program:villen_api]
command=/path/to/venv/bin/gunicorn villen.wsgi:application --bind 127.0.0.1:8001
environment=DJANGO_SETTINGS_MODULE="villen.settings.api"
directory=/home/villen/Desktop/project/web
user=villen
autostart=true
autorestart=true
stdout_logfile=/var/log/villen/api.log
stderr_logfile=/var/log/villen/api.err.log

[program:villen_tools]
command=/path/to/venv/bin/gunicorn villen.wsgi:application --bind 127.0.0.1:8002
environment=DJANGO_SETTINGS_MODULE="villen.settings.tools"
directory=/home/villen/Desktop/project/web
user=villen
autostart=true
autorestart=true
stdout_logfile=/var/log/villen/tools.log
stderr_logfile=/var/log/villen/tools.err.log

[program:villen_blog]
command=/path/to/venv/bin/gunicorn villen.wsgi:application --bind 127.0.0.1:8003
environment=DJANGO_SETTINGS_MODULE="villen.settings.blog"
directory=/home/villen/Desktop/project/web
user=villen
autostart=true
autorestart=true
stdout_logfile=/var/log/villen/blog.log
stderr_logfile=/var/log/villen/blog.err.log

[program:villen_www]
command=/path/to/venv/bin/gunicorn villen.wsgi:application --bind 127.0.0.1:8004
environment=DJANGO_SETTINGS_MODULE="villen.settings.www"
directory=/home/villen/Desktop/project/web
user=villen
autostart=true
autorestart=true
stdout_logfile=/var/log/villen/www.log
stderr_logfile=/var/log/villen/www.err.log
