# Generated by Django 5.2.1 on 2025-12-02 18:27

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('source_code_url', models.URLField(blank=True, max_length=500, null=True)),
                ('detailed_content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('category', models.CharField(default='General', max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_tier', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('approved_tier', models.CharField(blank=True, choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20)),
                ('requested_duration', models.PositiveIntegerField(choices=[(30, '1 Month'), (90, '3 Months'), (180, '6 Months'), (365, '1 Year'), (0, 'Lifetime')], default=30)),
                ('approved_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('request_reason', models.TextField(blank=True, help_text="User's reason for requesting premium")),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (visible to user if provided)')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to user)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Premium Requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', '-requested_at'], name='tools_premi_status_8eefff_idx'), models.Index(fields=['user', 'status'], name='tools_premi_user_id_93bc40_idx')],
            },
        ),
        migrations.CreateModel(
            name='ToolReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tools.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tool', 'user')},
            },
        ),
    ]
