# Generated by Django 5.2.1 on 2025-11-27 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiumrequest',
            options={'ordering': ['-requested_at'], 'verbose_name_plural': 'Premium Requests'},
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (visible to user if provided)'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_requests_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='premiumrequest',
            index=models.Index(fields=['status', '-requested_at'], name='tools_premi_status_8eefff_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumrequest',
            index=models.Index(fields=['user', 'status'], name='tools_premi_user_id_93bc40_idx'),
        ),
    ]
