# Generated by Django 5.2.2 on 2025-06-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='image',
        ),
        migrations.AddField(
            model_name='tool',
            name='documentation_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='source_code_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
