# Generated by Django 5.2.8 on 2025-11-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_premiumrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes (not visible to user)'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='approved_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='approved_tier',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='request_reason',
            field=models.TextField(blank=True, help_text="User's reason for requesting premium"),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='requested_duration',
            field=models.PositiveIntegerField(choices=[(30, '1 Month'), (90, '3 Months'), (180, '6 Months'), (365, '1 Year'), (0, 'Lifetime')], default=30),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='requested_tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='basic', max_length=20),
        ),
    ]
