# Generated by Django 5.2.1 on 2025-11-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_premiumrequest_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
